sudo: required
services:
  - docker

before_install:
  - docker build -t chsunny548/react-test -f client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chsunny548/react-test npm test -- --coverage

after_success:
  - docker build -t chsunny548/multi-client ./client
  - docker build -t chsunny548/multi-nginx ./nginx
  - docker build -t chsunny548/multi-server ./server
  - docker build -t chsunny548/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push chsunny548/multi-client
  - docker push chsunny548/multi-nginx
  - docker push chsunny548/multi-worker
  - docker push chsunny548/multi-server

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multii-docker
  env: MultiiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-536311552047
  bucket_path: docker-multii
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
